from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("method", models.CharField(max_length=10)),
                ("source", models.CharField(default="middleware", max_length=20)),
                ("action", models.CharField(default="request", max_length=50)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "tenant_schema",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("tenant_id", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"]),
                    models.Index(fields=["user"]),
                    models.Index(fields=["source"]),
                    models.Index(fields=["tenant_schema"]),
                    models.Index(fields=["action"]),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_schema",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("days", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [models.Index(fields=["tenant_schema"])],
                "verbose_name": "Audit Retention Policy",
                "verbose_name_plural": "Audit Retention Policies",
            },
        ),
    ]


# Generated by Django 4.2.27 on 2025-12-21 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("method", models.CharField(max_length=10)),
                ("source", models.CharField(default="middleware", max_length=20)),
                ("action", models.CharField(default="request", max_length=50)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "tenant_schema",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("tenant_id", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_schema",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                ("days", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Audit Retention Policy",
                "verbose_name_plural": "Audit Retention Policies",
                "indexes": [
                    models.Index(
                        fields=["tenant_schema"], name="auditing_au_tenant__61762d_idx"
                    )
                ],
            },
        ),
    ]
